import React from "react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service - Yuvaya",
  description: "Read Yuvaya's official Terms and Conditions of Service. Understand our terms regarding purchases, product usage, allergen disclaimers, subscriptions, and general user conditions.",
};

const TermsOfService = () => {
  return (
    <main className="min-h-screen bg-[#fffdf2] pt-20">
      {/* Header Banner */}
      <header className="bg-[#26312d] py-16 md:py-24 px-4 text-center border-b border-[#014d07]/10">
        <div className="max-w-4xl mx-auto">
          <span className="font-switzer text-xs md:text-sm uppercase tracking-widest text-[#fffdf2]/60 font-medium mb-3 block">
            Legal Policies
          </span>
          <h1 className="font-cormorant text-4xl sm:text-5xl md:text-6xl font-bold text-[#fffdf2] leading-tight">
            Terms of Service
          </h1>
          <div className="w-16 h-1 bg-[#fffdf2]/30 mx-auto mt-6 rounded-full" />
        </div>
      </header>

      {/* Content Area */}
      <article className="max-w-4xl mx-auto px-6 py-16 sm:py-24 font-switzer text-[#3d3d3d] leading-relaxed text-[15px] sm:text-[17px]">
        {/* Intro Section */}
        <section className="mb-12">
          <p className="mb-6 font-light">
            This document is an electronic record in terms of Information Technology Act, 2000 (“IT Act”) and rules issued thereunder, as applicable and the provisions pertaining to electronic records in various statutes as amended by the IT Act and is published in accordance with the provisions of applicable laws, including the Consumer Protection (E-Commerce) Rules 2020, that require publishing the rules and regulations, privacy policy and terms and conditions for access or usage of the website. This electronic record is generated by a computer system and does not require any physical or digital signatures.
          </p>
          <p className="mb-6 font-light">
            Please read these terms and conditions (“T&C”) carefully. By accessing, browsing,{" "}
            <a href="https://www.shopyuvaya.com" target="_blank" rel="noopener noreferrer" className="text-[#34803c] font-medium hover:underline">
              www.shopyuvaya.com
            </a>{" "}
            or any other website, mobile version of the website or mobile application (together the “Website”) or availing any of the products of AQAI Health Limited Liability Partnership (hereinafter referred to as “Company” or “us” or “we”), you, including the persons who browse or the persons who order the product, agree to be bound by all of the T&C mentioned hereunder.
          </p>
          <p className="mb-6 font-light">
            The domain name and website Yuvaya is owned by AQAI Health Limited Liability Partnership, having its registered office at G-236, B-Wing, Ground Floor, Express Zone Mall, Western Express Highway, Goregaon East, Mumbai - 400063, Maharashtra, India.
          </p>
          <p className="mb-6 font-light">
            AQAI Health Limited Liability Partnership is licensed to use and operate the site and supply products directly to customers who transact using the site. As a user of the site and its services you are contracting with AQAI Health Limited Liability Partnership through these terms.
          </p>
          <p className="mb-6 font-light">
            Only persons who can enter into a legally binding contract under the Indian Contract Act, 1872 can use the Website and/or transact on the Website. Any minor who wishes to use or access the Website is required to conduct such transaction through their legal guardian or parents. If you represent a company, partnership firm or sole proprietorship, you shall be eligible to access and use the Website to conduct the transactions on its behalf only if you have been duly authorized by way of necessary corporate action, as may be prescribed statutorily and/or under the charter documents of such entity.
          </p>
          <p className="mb-6 font-light">
            The Company reserves the right to amend or revise the T&C at any time by uploading a revised or amended T&C on the Website with or without prior notice. The amended T&C will be effective immediately after it is uploaded on this Website. Your access or use of the Website following any such changes constitutes your acceptance to follow and you shall be bound by these T&C, as amended. The version of the T&C that will apply to your order will be those uploaded on the Website at the time you use, access, or place your order. For this reason, we encourage you to review these T&C each time you access and place your order.
          </p>
          <p className="mb-6 font-light">
            These Terms of Service apply to all users of the Website, including without limitation users who are browsers, customers, merchants, and/or contributors of content.
          </p>
          <p className="mb-6 font-light">
            We offer this Website, including all information, tools and services available from this Website to you, the user, conditioned upon your acceptance of all terms, conditions, policies and notices stated here. Before you click, sip, or checkout, please read these Terms of Service carefully. By using any part of this website, you’re agreeing to these rules. If you're not okay with any part of the terms, we kindly ask you not to use the site or services. If these Terms are considered an offer, then your acceptance is limited strictly to these Terms of Service. Any new features or tools which are added to the Website shall also be subject to the Terms of Service.
          </p>
          <p className="mb-6 font-light">
            By visiting our website and/or purchasing any product listed on the Website, you engage in our services provided via the Website (“Service”) and agree to be bound by the following terms and conditions (“Terms of Service”), including those additional terms and conditions and policies referenced herein and/or available by hyperlink. You should read these Terms of Service and access and read all further linked information, if any, referred to in these Terms of Service, as such information contains further terms and conditions that apply to you as a user of the Website. Such linked information including but not limited to our privacy policy (“Privacy Policy”) is hereby incorporated by reference into these Terms of Service.
          </p>
          <p className="mb-6 font-light">
            You may only access the Website for lawful purposes. You are solely responsible for the knowledge of and adherence to any and all laws, rules, and regulations pertaining to your use of the Website. We reserve the right to block any user and permanently disable a user account if we believe in our sole discretion that the action of such user has resulted in breach of the fair usage policy or T&C. If you are unwilling or unable to be legally bound by these Terms of Service, please do not give your consent or use the Website. You cannot accept these Terms of Service if:
          </p>
          <ul className="list-disc pl-6 mb-6 font-light space-y-2">
            <li>you are not lawfully entitled to use the Website; or</li>
            <li>you are not of legal age to form a binding agreement with us.</li>
          </ul>
        </section>

        {/* General Conditions */}
        <section className="mb-12">
          <h2 className="font-cormorant text-2xl sm:text-3xl font-semibold text-[#26312d] mt-10 mb-6 border-b border-[#26312d]/10 pb-2">
            General Conditions
          </h2>
          <div className="space-y-6 font-light">
            <div>
              <h3 className="font-cormorant text-lg sm:text-xl font-medium text-[#26312d] mb-2">
                Force Majeure
              </h3>
              <p>
                The Company will not be deemed in default hereunder or held responsible for any cessation, interruption or delay in the performance of its obligations hereunder due to earthquake, storm, natural disaster, act of God, war, terrorism, armed conflict, labor strike, lockout, or boycott, any acts of nature, labor disputes, floods, lightning, severe weather, shortages of materials, rationing, pandemic or epidemic, inducement of any virus, Trojan or other disruptive mechanisms, any event of hacking or illegal usage of the Website, utility or communication failures, revolution, civil commotion, acts of public enemies, blockade, embargo or any law, order, proclamation, regulation, ordinance, demand or requirement having legal effect of any government or any judicial authority or representative of any such government, or any other act whatsoever, whether similar or dissimilar to those referred to in this clause beyond our reasonable control. Further, if a Force Majeure event takes place that affects the performance of our obligations under these T&C, our obligations under these T&C shall be suspended for the duration of the Force Majeure event.
              </p>
            </div>
            <div>
              <h3 className="font-cormorant text-lg sm:text-xl font-medium text-[#26312d] mb-2">
                Cessation of Operation
              </h3>
              <p>
                The Company may at any time, in its sole discretion and without advance notice to you, cease operation of the Website and distribution of the Products.
              </p>
            </div>
            <div>
              <h3 className="font-cormorant text-lg sm:text-xl font-medium text-[#26312d] mb-2">
                Entire Agreement
              </h3>
              <p>
                This T&C comprises the entire agreement between you and the Company and supersedes any prior agreements pertaining to the subject matter contained herein.
              </p>
            </div>
            <div>
              <h3 className="font-cormorant text-lg sm:text-xl font-medium text-[#26312d] mb-2">
                Effect of Waiver
              </h3>
              <p>
                The failure of the Company to exercise or enforce any right or provision of this T&C will not constitute a waiver of such right or provision. If any provision of this T&C is found by a court of competent jurisdiction to be invalid, the parties nevertheless agree that the court should endeavor to give effect to the parties’ intentions as reflected in such provision, and the other provisions of this T&C remain in full force and effect.
              </p>
            </div>
            <div>
              <h3 className="font-cormorant text-lg sm:text-xl font-medium text-[#26312d] mb-2">
                Governing Law and Jurisdiction
              </h3>
              <p>
                This T&C shall be construed in accordance with the applicable laws of India and will be governed by the laws of the state of Maharashtra without regard to its conflict of law principles to the contrary. Neither you nor the Company will commence or prosecute any suit, proceeding or claim to enforce the provisions of this T&C, to recover damages for breach of or default of this T&C, or otherwise arising under or by reason of this T&C, other than in courts located in the State of Maharashtra. By using this Website or ordering Products, you consent to the jurisdiction and venue of such courts in connection with any action, suit, proceeding or claim arising under or by reason of this T&C.
              </p>
            </div>
            <div>
              <h3 className="font-cormorant text-lg sm:text-xl font-medium text-[#26312d] mb-2">
                Waiver of Class Action Rights
              </h3>
              <p>
                By accepting the T&C, you hereby irrevocably waive any right you may have to join claims with those of others in the form of a class action or similar procedural device; any claims arising out of, relating to, or in connection with this T&C must be asserted individually.
              </p>
            </div>
            <div>
              <h3 className="font-cormorant text-lg sm:text-xl font-medium text-[#26312d] mb-2">
                Termination
              </h3>
              <p>
                The Company reserves the right to terminate your access to the Website if it reasonably believes, in its sole discretion, that you have breached any of the terms of this T&C. Following termination, you will not be permitted to use the Website and the Company may, in its sole discretion and without advance notice to you, cancel any outstanding orders for Products. If your access to the Website is terminated, the Company reserves the right to exercise whatever means it deems necessary to prevent the unauthorized access of the Website. This T&C will survive indefinitely, unless and until the Company chooses, in its sole discretion and without advance notice to you, to terminate it.
              </p>
            </div>
            <div>
              <h3 className="font-cormorant text-lg sm:text-xl font-medium text-[#26312d] mb-2">
                Domestic Use
              </h3>
              <p>
                The Company makes no representation that the Website or Products are appropriate or available for use in locations outside India. The users who access the Website from outside India do so at their own risk and initiative and must bear all responsibility for compliance with any applicable local laws.
              </p>
            </div>
            <div>
              <h3 className="font-cormorant text-lg sm:text-xl font-medium text-[#26312d] mb-2">
                Assignment & Survival
              </h3>
              <p className="mb-2">
                You may not assign your rights and obligations under this T&C to anyone. The Company may assign its rights and obligations under this T&C in its sole discretion and without advance notice to you.
              </p>
              <p>
                If any provision or provisions of these T&C shall be held to be invalid, illegal, or unenforceable, the validity, legality and enforceability of the remaining provisions shall remain in full force and effect.
              </p>
            </div>
          </div>
        </section>

        {/* Product Usage */}
        <section className="mb-12">
          <h2 className="font-cormorant text-2xl sm:text-3xl font-semibold text-[#26312d] mt-10 mb-6 border-b border-[#26312d]/10 pb-2">
            Product Usage & Guidelines
          </h2>
          <p className="mb-6 font-medium text-[#26312d]">
            By purchasing and using any nutraceutical supplement from this establishment, you agree to the following terms and conditions:
          </p>
          <div className="space-y-6 font-light">
            <div>
              <h3 className="font-cormorant text-lg sm:text-xl font-medium text-[#26312d] mb-2">
                Product Use & Dosage
              </h3>
              <p className="mb-2">
                This supplement is intended for use by adults above 18 years of age, unless prescribed by a healthcare professional. It is not a substitute for a varied diet and healthy lifestyle. The products and services available on the Site, and the samples, if any, that AQAI may provide you, are for your personal and/or professional use only. The products or services, or samples thereof, which you may receive from us, shall not be sold or resold for any commercial reasons.
              </p>
              <p>
                Do not exceed the recommended dosage unless advised by a qualified healthcare professional.
              </p>
            </div>
            <div>
              <h3 className="font-cormorant text-lg sm:text-xl font-medium text-[#26312d] mb-2">
                Storage
              </h3>
              <p>
                Store the product in a cool, dry place, away from direct sunlight and moisture. Keep out of reach of children.
              </p>
            </div>

            {/* Medical Disclaimer Box */}
            <div className="border border-[#26312d]/10 bg-[#26312d]/5 rounded-2xl p-6 md:p-8 mt-6 mb-6">
              <h3 className="font-cormorant text-lg sm:text-xl font-semibold text-[#26312d] mb-3 uppercase tracking-wider">
                Medical Disclaimer
              </h3>
              <p className="mb-4">
                The products, services, and information provided—including consultations, blogs, and other materials—are for informational purposes only and do not constitute medical advice, diagnosis, or treatment. Our products are not intended to treat, cure, or prevent any disease. They are not a substitute for professional medical advice from your doctor or healthcare provider. If you are pregnant, lactating, taking medication, or have an existing medical condition, consult your physician before using our products.
              </p>
              <p className="mb-4">
                If you experience any adverse reactions after using our products, discontinue use immediately and seek medical attention.
              </p>
              <p className="mb-4">
                We provide personalized product recommendations based on the information you share through our platform. However, if you have a recurring or previously diagnosed health concern, or are on prescription medication, seek medical advice from a qualified healthcare professional before making dietary or lifestyle changes. We reserve the right, with or without notice, to cancel or reduce the quantity of any Products to be provided to you that we believe, in our sole discretion, may result in the violation of our T&C.
              </p>
              <p className="mb-4">
                The Company may change, suspend, or discontinue the availability of any of the Products at any time, without any notice or liability. You acknowledge that the price payable in connection with the Product or any service, may be subject to change, without notice or liability.
              </p>
              <p>
                While we make every effort to ensure the accuracy of medical information on this platform, we do not guarantee that it reflects the most up-to-date research. You should always consult a licensed healthcare provider for medical concerns. Never disregard professional medical advice or delay seeking treatment due to information found on this platform.
              </p>
            </div>
          </div>
        </section>

        {/* Allergen Disclaimer & Consumer Responsibility */}
        <section className="mb-12 border border-amber-200/60 bg-amber-50/40 rounded-2xl p-6 md:p-8">
          <h2 className="font-cormorant text-2xl sm:text-3xl font-semibold text-[#26312d] mb-4">
            Allergen Disclaimer & Consumer Responsibility
          </h2>
          <div className="space-y-4 font-light">
            <div>
              <h3 className="font-cormorant text-lg sm:text-xl font-medium text-[#26312d] mb-2">
                Important Product Information:
              </h3>
              <p>
                Certain products sold by Yuvaya contain ingredients derived from fish and marine sources. Additionally, all our products are manufactured in facilities that also process milk, soy, tree nuts, and other common allergens.
              </p>
            </div>
            <div>
              <h3 className="font-cormorant text-lg sm:text-xl font-medium text-[#26312d] mb-2">
                Your Responsibilities:
              </h3>
              <p className="mb-2">
                By purchasing from Yuvaya, you expressly acknowledge and agree that:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>
                  <strong>Due Diligence:</strong> It is your sole responsibility to carefully review the complete ingredient list, nutritional information, and allergen warnings displayed on product pages and packaging before making a purchase.
                </li>
                <li>
                  <strong>Individual Variability:</strong> Individual responses to nutritional supplements vary significantly based on personal health conditions, genetic factors, pre-existing allergies, sensitivities, current medications, and other unique physiological factors.
                </li>
                <li>
                  <strong>Medical Consultation:</strong> You are solely responsible for consulting with a qualified healthcare professional or registered dietitian before using our products, especially if you have known food allergies, pre-existing conditions, are pregnant/nursing, are taking medications, or are under 18 years of age.
                </li>
                <li>
                  <strong>Assumption of Risk:</strong> You assume all risks associated with the purchase, storage, and consumption of our products.
                </li>
              </ul>
            </div>
          </div>
        </section>

        {/* Product Information */}
        <section className="mb-12">
          <h2 className="font-cormorant text-2xl sm:text-3xl font-semibold text-[#26312d] mt-10 mb-6 border-b border-[#26312d]/10 pb-2">
            Product Information & Pricing
          </h2>
          <p className="mb-4 font-light">
            In the preparation of the content for the Platforms, in particular to the prices of the products, we have taken reasonable care to ensure that the prices quoted are correct at the time of publishing and that all products have been adequately described. All prices are displayed inclusive of all taxes. If you purchase any Products, you will be responsible for paying any applicable taxes in relation to such purchase.
          </p>
          <p className="mb-4 font-light">
            AQAI attempts to be as accurate as possible in the description of the product on the Site. However, AQAI does not warrant that the product description, color, information or other content of the Site is accurate, complete, reliable, current or error-free. The Site may contain typographical errors or inaccuracies and may not be complete or current. The product pictures are indicative and may not match the actual product. Packaging of the products may vary from that shown on the Platforms. The weights, dimensions and capacities given are approximate only.
          </p>
          <p className="mb-6 font-light">
            We have made every effort to display as accurately as possible the colors of our products that appear on the Platforms. However, as the actual colors you see will depend on your monitor/phone screen, we cannot guarantee that your monitor's/phone screen’s display of any colour will accurately reflect the colour of the product on delivery.
          </p>
          <p className="mb-6 font-light">
            AQAI reserves the right to correct, change or update information, errors, inaccuracies or omissions at any time (including after an order has been submitted) without prior notice. Please note that such errors, inaccuracies or omissions may also relate to pricing and availability of the product or services. We are responsible solely for the content available regarding our products/services on the Platforms as provided by us. We shall not be held accountable for reliance placed on information available on any other platform(s)/Website(s), including but not limited to social media platforms, unless affirmed by us prior to such reliance.
          </p>
        </section>

        {/* Subscription Plan */}
        <section className="mb-12">
          <h2 className="font-cormorant text-2xl sm:text-3xl font-semibold text-[#26312d] mt-10 mb-6 border-b border-[#26312d]/10 pb-2">
            Subscription Plan and Payment Terms
          </h2>
          <p className="mb-4 font-light">
            In addition to being able to purchase products from the Website, you may also purchase Products on a subscription plan. The users shall have the ability to purchase the Products on a monthly or fortnightly subscription or in such other manner as may be decided by us and notified to you from time to time (“Subscription”).
          </p>
          <p className="mb-4 font-light">
            When you purchase a Subscription (“Transaction”), we may ask you to supply additional information relevant to your Transaction, such as your debit or credit card number, the expiration date of your debit or credit card, or bank account details and your address(es) for billing and delivery (“Payment Information”). You represent and warrant that you have the legal right to use all payment method(s) represented by any such Payment Information.
          </p>
          <p className="mb-4 font-light">
            The amounts due and payable by you for a Transaction will be presented to you before you place your order. If you choose to initiate a Transaction, you consent and authorize us to provide your Payment Information to third party service providers for completion of the Transaction, and you further agree to: (a) pay all of the applicable fees and any taxes thereon; (b) bear any additional costs, charges, expenses (including fees and taxes thereon) that your bank or other financial service provider may levy in relation to the Transaction; and (c) permit us to charge your debit or credit card or third-party payment processing account, for verification, pre-authorization and payment purposes. You will receive a confirmation email after we confirm the payment for your order. Your order is not binding on us until accepted and confirmed by us. All payments made are non-refundable and non-transferable except as expressly provided under these Terms of Service.
          </p>
          <p className="mb-6 font-light">
            All amounts are payable and charged for monthly or fortnightly Subscriptions or as per our payment cycle, at the beginning of the Subscription. Each such Subscription renews automatically for an additional period equal in length to the expiring Subscription term until you cancel it, using the Payment Information you have provided. You must cancel your monthly or fortnightly Subscription before it renews to avoid the billing of the fees for the next Subscription period. You can cancel the renewal of your subscription at any time by contacting us by email at{" "}
            <a href="mailto:hello@yuvaya.in" className="text-[#34803c] font-medium hover:underline">
              hello@yuvaya.in
            </a>
            . You will not receive a refund for the fees you already paid for your current Subscription period and you will continue to receive the services ordered until the end of your current Subscription period. We have no obligation to keep you informed prior to the billing of the fees based on your Subscription. You may see your Subscription related information in “My Account” on the Website. In case of any request in relation to product customization, you are required to inform us at{" "}
            <a href="mailto:hello@yuvaya.in" className="text-[#34803c] font-medium hover:underline">
              hello@yuvaya.in
            </a>{" "}
            at least 3 (three) business days in advance of the next billing cycle. The billing amount may change subject to the change in product plan.
          </p>

          {/* Non-Refundable Conditions Highlight Box */}
          <div className="border border-red-200 bg-red-50/20 rounded-2xl p-6 md:p-8 mt-6 mb-6">
            <h3 className="font-cormorant text-lg sm:text-xl font-semibold text-red-950 mb-3 uppercase tracking-wider">
              Non-Refundable Conditions
            </h3>
            <p className="mb-4 font-light text-red-900">
              The following situations are expressly excluded from our return and refund policy:
            </p>
            <ul className="list-disc pl-6 space-y-2 font-light text-red-900">
              <li>
                <strong>Opened or Used Products:</strong> Once the product seal has been broken, or the product has been opened, consumed, or used in any manner, it becomes permanently non-returnable and non-refundable.
              </li>
              <li>
                <strong>Allergic Reactions or Adverse Effects:</strong> No refunds, returns, replacements, or exchanges will be provided for products that cause allergic reactions, sensitivities, digestive discomfort, adverse effects, or any negative individual response.
              </li>
              <li>
                <strong>Subjective Dissatisfaction:</strong> Products cannot be returned due to personal dissatisfaction with taste, texture, flavor, smell, perceived efficacy, or results after the product has been opened or consumed.
              </li>
              <li>
                <strong>Change of Mind:</strong> Post-purchase change of mind or buyer's remorse does not qualify for returns or refunds once the order has been delivered.
              </li>
            </ul>
            <p className="mt-4 font-light text-red-950">
              We strongly encourage customers to contact our support team at{" "}
              <a href="mailto:hello@yuvaya.in" className="text-[#34803c] font-medium hover:underline">
                hello@yuvaya.in
              </a>{" "}
              with any questions regarding ingredients, allergens, dosage, or product suitability before completing your purchase.
            </p>
          </div>
        </section>

        {/* Limitation of Liability */}
        <section className="mb-12 border border-[#26312d]/10 bg-[#26312d]/5 rounded-2xl p-6 md:p-8">
          <h2 className="font-cormorant text-2xl sm:text-3xl font-semibold text-[#26312d] mb-4">
            Limitation of Liability
          </h2>
          <p className="mb-4 font-light">
            By completing your purchase on{" "}
            <a href="https://www.shopyuvaya.com" target="_blank" rel="noopener noreferrer" className="text-[#34803c] font-medium hover:underline">
              www.shopyuvaya.com
            </a>
            , you acknowledge and agree that:
          </p>
          <p className="mb-4 font-light">
            Yuvaya, its parent company, subsidiaries, affiliates, directors, officers, employees, agents, manufacturers, suppliers, and distributors shall not be held liable for any direct, indirect, incidental, consequential, special, punitive, or exemplary damages arising from:
          </p>
          <ul className="list-disc pl-6 space-y-2 font-light mb-4">
            <li>Allergic reactions or adverse health effects resulting from product consumption</li>
            <li>Individual sensitivities or intolerances to ingredients</li>
            <li>Interactions with medications, supplements, or pre-existing health conditions</li>
            <li>Failure to achieve desired results or perceived lack of efficacy</li>
            <li>Any health-related consequences resulting from use, misuse, or discontinuation of our products</li>
          </ul>
          <p className="font-light">
            This limitation of liability applies to the fullest extent permitted under applicable Indian law, including but not limited to the Consumer Protection Act, 2019.
          </p>
        </section>

        {/* Marketplace Purchases */}
        <section className="mb-12">
          <h2 className="font-cormorant text-2xl sm:text-3xl font-semibold text-[#26312d] mt-10 mb-6 border-b border-[#26312d]/10 pb-2">
            Marketplace Purchases
          </h2>
          <p className="mb-4 font-light">
            If you have purchased Yuvaya products through third-party e-commerce platforms or marketplaces (including but not limited to Amazon, Flipkart, Nykaa, or any other online retail partner), please note the following:
          </p>
          <div className="space-y-4 font-light">
            <div>
              <h3 className="font-cormorant text-lg sm:text-xl font-medium text-[#26312d] mb-2">
                Primary Responsibility
              </h3>
              <ul className="list-disc pl-6 space-y-2">
                <li>All returns, refunds, cancellations, replacements, and order-related concerns for marketplace purchases must be raised directly with the respective marketplace platform where the purchase was made.</li>
                <li>Each marketplace has its own independent returns, refunds, and customer service policies that govern transactions completed on their platform.</li>
                <li>Yuvaya has limited ability to directly process returns, refunds, or replacements for orders placed through third-party marketplaces, as these transactions are subject to the marketplace's terms and conditions.</li>
              </ul>
            </div>
            <div>
              <h3 className="font-cormorant text-lg sm:text-xl font-medium text-[#26312d] mb-2">
                Our Support Commitment
              </h3>
              <p className="mb-2">
                While we are happy to assist marketplace customers to the best of our abilities with product-related queries, ingredient information, or usage guidance, we cannot guarantee resolution of order-specific issues (returns, refunds, delivery concerns, order modifications).
              </p>
              <p className="mb-2">
                For the fastest resolution of marketplace order issues, we strongly recommend contacting the marketplace customer care team directly through their official channels.
              </p>
              <p>
                If you require our assistance with a marketplace order, please contact us at{" "}
                <a href="mailto:hello@yuvaya.in" className="text-[#34803c] font-medium hover:underline">
                  hello@yuvaya.in
                </a>{" "}
                with your marketplace order details, and we will attempt to coordinate with the platform on your behalf, though we cannot guarantee any specific outcome.
              </p>
            </div>
          </div>
        </section>

        {/* Website Usage & IP */}
        <section className="mb-12">
          <h2 className="font-cormorant text-2xl sm:text-3xl font-semibold text-[#26312d] mt-10 mb-6 border-b border-[#26312d]/10 pb-2">
            Website Use & Intellectual Property
          </h2>
          <div className="space-y-6 font-light">
            <div>
              <h3 className="font-cormorant text-lg sm:text-xl font-medium text-[#26312d] mb-2">
                Content & Intellectual Property
              </h3>
              <p>
                The Website offers information and marketing materials, both directly and through indirect links to third-party websites about nutritional and dietary supplements. The Company does not always create such information and content; instead, it is gathered from other sources. The Company does not endorse any such information or content and disclaims all liability in connection with it.
              </p>
              <p className="mt-2">
                To the extent that the Company does create the content, such content is protected by intellectual property laws of India. Any unauthorized use of the material may violate copyright, trademark, and/or other laws. You acknowledge that your use of the content on this Website is for personal and non-commercial use. We respect the intellectual property of others. If you feel your work has been copied in a way that constitutes copyright infringement, you can write to us at{" "}
                <a href="mailto:hello@yuvaya.in" className="text-[#34803c] font-medium hover:underline">
                  hello@yuvaya.in
                </a>.
              </p>
            </div>
            <div>
              <h3 className="font-cormorant text-lg sm:text-xl font-medium text-[#26312d] mb-2">
                Use of Website
              </h3>
              <p>
                You will not use the Website for any illegal purposes. You will: (a) abide by all applicable local, state, national, and international laws and regulations; (b) not interfere with or disrupt the use and enjoyment of the Website by other users; (c) not resell material on the Website; (d) not transmit spam, chain letters, or unsolicited communications; and (e) not defame, harass, abuse, or disrupt other users.
              </p>
            </div>
            <div>
              <h3 className="font-cormorant text-lg sm:text-xl font-medium text-[#26312d] mb-2">
                Site Security
              </h3>
              <p>
                You are prohibited from violating or attempting to violate the security of the Website, including accessing data not intended for you, attempting to probe/scan system vulnerability, or attempting to interfere with service to any other user by submitting a virus, overloading, flooding, or crashing. Violations of system or network security may result in civil or criminal liability.
              </p>
            </div>
          </div>
        </section>

        {/* Payment and Tracking */}
        <section className="mb-12">
          <h2 className="font-cormorant text-2xl sm:text-3xl font-semibold text-[#26312d] mt-10 mb-6 border-b border-[#26312d]/10 pb-2">
            Payment & Tracking
          </h2>
          <div className="space-y-4 font-light">
            <p>
              <strong>Payment Methods:</strong> Payments for the Products available on the Website may be made via Credit Cards, Debit Cards, Net Banking, Wallets, UPI, QR, PayPal, Reward Points, or Cash on Delivery.
            </p>
            <p>
              <strong>Order Tracking:</strong> Upon dispatch of the Product, you will receive an email with the details of the tracking number and the courier company. Orders may also be tracked by clicking the ‘Your orders’ option on your My Accounts page after 24 hours from the time of dispatch.
            </p>
          </div>
        </section>

        {/* Contact and Grievance Desk */}
        <section className="mb-12">
          <h2 className="font-cormorant text-2xl sm:text-3xl font-semibold text-[#26312d] mt-10 mb-6 border-b border-[#26312d]/10 pb-2">
            Contact & Grievance Redressal
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 font-light">
            <div className="bg-[#26312d]/5 rounded-2xl p-6 border border-[#26312d]/10">
              <h3 className="font-cormorant text-lg sm:text-xl font-semibold text-[#26312d] mb-3">
                Customer Service Desk
              </h3>
              <p className="mb-1"><strong>Email:</strong> <a href="mailto:hello@yuvaya.in" className="text-[#34803c] font-medium hover:underline">hello@yuvaya.in</a></p>
              <p className="mb-1"><strong>Phone:</strong> <a href="tel:+919011390116" className="text-[#34803c] font-medium hover:underline">+91 9011390116</a></p>
              <p><strong>Hours:</strong> Monday–Friday (10 am to 7 pm)</p>
            </div>
            <div className="bg-[#26312d]/5 rounded-2xl p-6 border border-[#26312d]/10">
              <h3 className="font-cormorant text-lg sm:text-xl font-semibold text-[#26312d] mb-3">
                Grievance Officer
              </h3>
              <p className="mb-1"><strong>Officer:</strong> Palak Agarwal</p>
              <p className="mb-1"><strong>Email:</strong> <a href="mailto:hello@yuvaya.in" className="text-[#34803c] font-medium hover:underline">hello@yuvaya.in</a></p>
              <p className="mb-1"><strong>Phone:</strong> <a href="tel:+919011390116" className="text-[#34803c] font-medium hover:underline">+91 9011390116</a></p>
              <p className="mb-2"><strong>Address:</strong> G-236, B-wing, Ground floor, Express Zone mall, Western Express Highway, Goregaon East, Mumbai 400063</p>
              <p><strong>Hours:</strong> Monday–Friday (10 am to 6:30 pm)</p>
            </div>
          </div>
        </section>

        {/* Scam Warning Alert Box */}
        <section className="border border-red-200 bg-red-50/20 rounded-2xl p-6 md:p-8 mt-12 mb-12">
          <h2 className="font-cormorant text-xl sm:text-2xl font-bold text-red-950 mb-3 uppercase tracking-wider flex items-center gap-2">
            ⚠️ Important Scam Warning
          </h2>
          <p className="mb-4 font-light text-red-900 leading-relaxed">
            It has recently come to our attention that a scam is circulating within our industry, targeting B2B customers with fraudulent offers of substantial discounts and enticing freebies, such as free laptops against minimum purchase orders. These offers are often accompanied by forged documents that appear genuine but have fraudulent bank account details.
          </p>
          <p className="mb-4 font-light text-red-900 leading-relaxed">
            To protect yourself, please verify the authenticity of any offer for Yuvaya products before making a purchase. For verification, you can contact our support team at <a href="tel:+919011390116" className="text-[#34803c] font-medium hover:underline">+91 9011390116</a> or write to us at <a href="mailto:hello@yuvaya.in" className="text-[#34803c] font-medium hover:underline">hello@yuvaya.in</a> before placing your order. Our team will confirm whether the offer you have received for Yuvaya products is genuine.
          </p>
          <p className="font-light text-red-950 leading-relaxed font-medium">
            We care about the safety of your business and urge you to be cautious to prevent falling victim to these scams.
          </p>
        </section>
      </article>
    </main>
  );
};

export default TermsOfService;