import type { Metadata } from "next";
import { Antic_Didone, Cormorant_Garamond, Poppins } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const cormorant_garamond = Cormorant_Garamond({
  variable: "--font-cormorant",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

const anti_didone = Antic_Didone({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-anti-didone",
})

const newTitle = localFont({
  src: [
    {
      path: "../public/Fonts/new-title-font-family/NewTitle-Extralight.otf",
      weight: "200",
      style: "normal",
    },
    {
      path: "../public/Fonts/new-title-font-family/NewTitle-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/Fonts/new-title-font-family/NewTitle-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/Fonts/new-title-font-family/NewTitle-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/Fonts/new-title-font-family/NewTitle-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-new-title",
});

const ttRamillas = localFont({
  src: [
    {
      path: "../public/Fonts/TT Ramillas Trial ExtraLight.ttf",
      weight: "200",
      style: "normal",
    },
    {
      path: "../public/Fonts/TT Ramillas Trial Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/Fonts/TT Ramillas Trial Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/Fonts/TT Ramillas Trial Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/Fonts/TT Ramillas Trial Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/Fonts/TT Ramillas Trial ExtraBold.ttf",
      weight: "800",
      style: "normal",
    },
    {
      path: "../public/Fonts/TT Ramillas Trial Black.ttf",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-tt-ramillas",
});

const switzer = localFont({
  src: [
    {
      path: "../public/Fonts/Switzer-Extralight.otf",
      weight: "200",
      style: "normal",
    },
    {
      path: "../public/Fonts/Switzer-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/Fonts/Switzer-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/Fonts/Switzer-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/Fonts/Switzer-Semibold.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/Fonts/Switzer-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/Fonts/Switzer-Extrabold.otf",
      weight: "800",
      style: "normal",
    },
    {
      path: "../public/Fonts/Switzer-Black.otf",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-switzer",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${cormorant_garamond.variable} ${poppins.variable} ${newTitle.variable} ${anti_didone.variable} ${ttRamillas.variable} ${switzer.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-white">{children}</body>
    </html>
  );
}
